const express=require('express'),path=require('path'),fs=require('fs'),cors=require('cors'),morgan=require('morgan'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs');
const {nanoid}=require('nanoid'); const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'lumora-demo-secret'; const DB=path.join(__dirname,'data/db.json');
app.use(cors());app.use(express.json());app.use(morgan('dev'));app.use(express.static(path.join(__dirname,'public')));
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8')),write=db=>fs.writeFileSync(DB,JSON.stringify(db,null,2)),clean=u=>{const {password,...x}=u;return x};
function auth(role){return(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);if(role&&req.user.role!==role)return res.status(403).json({message:'Forbidden'});next()}catch{return res.status(401).json({message:'Authentication required'})}}}
app.get('/api/health',(_,res)=>res.json({ok:true,service:'LUMORA Commerce API'}));
app.get('/api/products',(req,res)=>{let p=read().products;const{q,category,sort}=req.query;if(q)p=p.filter(x=>(x.name+x.category+x.description).toLowerCase().includes(q.toLowerCase()));if(category&&category!=='All')p=p.filter(x=>x.category===category);if(sort==='price-asc')p.sort((a,b)=>a.price-b.price);if(sort==='price-desc')p.sort((a,b)=>b.price-a.price);if(sort==='rating')p.sort((a,b)=>b.rating-a.rating);res.json(p)});
app.get('/api/products/:id',(req,res)=>{const p=read().products.find(x=>x.id===req.params.id);p?res.json(p):res.status(404).json({message:'Product not found'})});
app.post('/api/auth/login',async(req,res)=>{const db=read(),u=db.users.find(x=>x.email.toLowerCase()===String(req.body.email||'').toLowerCase());if(!u)return res.status(401).json({message:'Incorrect email or password'});const ok=u.password.startsWith('$2')?await bcrypt.compare(req.body.password,u.password):req.body.password===u.password;if(!ok)return res.status(401).json({message:'Incorrect email or password'});if(!u.password.startsWith('$2')){u.password=await bcrypt.hash(u.password,10);write(db)}const user=clean(u);res.json({user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})})});
app.post('/api/auth/register',async(req,res)=>{const{name,email,password}=req.body||{},db=read();if(!name||!email||!password||password.length<6)return res.status(400).json({message:'Complete all fields'});if(db.users.some(x=>x.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({message:'Email already registered'});const u={id:'u_'+nanoid(8),name,email:email.toLowerCase(),password:await bcrypt.hash(password,10),role:'customer'};db.users.push(u);write(db);const user=clean(u);res.status(201).json({user,token:jwt.sign(user,SECRET,{expiresIn:'7d'})})});
app.get('/api/orders/my',auth(),(req,res)=>res.json(read().orders.filter(x=>x.userId===req.user.id).reverse()));
app.post('/api/orders',(req,res)=>{const db=read(),{customer,email,address,items,userId}=req.body||{};if(!customer||!email||!address||!Array.isArray(items)||!items.length)return res.status(400).json({message:'Incomplete checkout'});let subtotal=0,normalized=[];for(const i of items){const p=db.products.find(x=>x.id===i.productId),qty=Math.max(1,+i.qty||1);if(!p||p.stock<qty)return res.status(400).json({message:'Insufficient stock'});subtotal+=p.price*qty;normalized.push({productId:p.id,name:p.name,price:p.price,qty});p.stock-=qty}const shipping=subtotal>=db.settings.shippingThreshold?0:15,tax=+(subtotal*db.settings.taxRate).toFixed(2),total=+(subtotal+shipping+tax).toFixed(2);const order={id:'ORD-'+Date.now().toString().slice(-7),userId:userId||null,customer,email,address,items:normalized,subtotal,shipping,tax,total,status:'Paid',date:new Date().toISOString().slice(0,10)};db.orders.push(order);write(db);res.status(201).json(order)});
app.get('/api/admin/summary',auth('admin'),(_,res)=>{const db=read(),revenue=db.orders.reduce((s,o)=>s+o.total,0);res.json({revenue,orders:db.orders.length,customers:db.users.filter(x=>x.role==='customer').length,products:db.products.length,lowStock:db.products.filter(x=>x.stock<10).length})});
app.get('/api/admin/orders',auth('admin'),(_,res)=>res.json(read().orders.reverse()));
app.patch('/api/admin/orders/:id',auth('admin'),(req,res)=>{const db=read(),o=db.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({message:'Order not found'});o.status=req.body.status||o.status;write(db);res.json(o)});
app.post('/api/admin/products',auth('admin'),(req,res)=>{const db=read(),p={id:'p_'+nanoid(7),rating:5,featured:false,badge:'New',...req.body,price:+req.body.price,stock:+req.body.stock};db.products.push(p);write(db);res.status(201).json(p)});
app.put('/api/admin/products/:id',auth('admin'),(req,res)=>{const db=read(),i=db.products.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({message:'Product not found'});db.products[i]={...db.products[i],...req.body,price:+req.body.price,stock:+req.body.stock};write(db);res.json(db.products[i])});
app.delete('/api/admin/products/:id',auth('admin'),(req,res)=>{const db=read(),i=db.products.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({message:'Product not found'});res.json(db.products.splice(i,1)[0]);write(db)});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public/index.html')));app.listen(PORT,()=>console.log(`LUMORA: http://localhost:${PORT}`));
